/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertEquals;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import models.Usuario;


@RunWith(PowerMockRunner.class)
@PrepareForTest(Usuario.class)
public class ConstrutorTest {	
	@Mock
    private Usuario mockUsuario;
    
    @Test public void testMetodoPrivado() throws Exception {        
    	Usuario usuario = new Usuario();
        usuario.setUsuario("fabricio");
        usuario.setSenha("fabricio123");
        usuario.setId(1);
        usuario.setNomeCompleto("Fabrício");
        
        PowerMockito.whenNew(Usuario.class).withNoArguments().thenReturn(usuario);
               
        assertEquals("fabricio", new Usuario().getUsuario());
    }
}
