/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import models.Cargo;
import models.Salario;


@RunWith(PowerMockRunner.class)
@PrepareForTest({ Salario.class, Cargo.class })
public class FinalTest {	
    @Before
    public void setUp() {
    }
    
    @Test public void testMetodoFinal() {
    	Salario salario = PowerMockito.mock(Salario.class);
    	
    	PowerMockito.when(salario.getValor()).thenReturn(10.00);
    	
    	assertEquals(10.00, salario.getValor(), 0);        
    }
    
    @Test public void testClasseFinal() {
    	Cargo cargo = PowerMockito.mock(Cargo.class);
    	
    	PowerMockito.when(cargo.getNome()).thenReturn("contador");
    	
    	assertEquals("contador", cargo.getNome());
    }
}
