/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import database.Conexao;


@RunWith(PowerMockRunner.class)
@PrepareForTest(Conexao.class)
public class MetodoEstaticoTest {
	 
	@Mock
    Conexao conexao;   
	
    @Before
    public void setUp() {
    }
    
    @Test public void testMetodoEstatico() {        
    	PowerMockito.mockStatic(Conexao.class);
    	
    	PowerMockito.when(Conexao.getInstancia()).thenReturn(null);
    	assertEquals(null, Conexao.getInstancia());        
    }
}
