/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import models.Usuario;


@RunWith(PowerMockRunner.class)
@PrepareForTest(Usuario.class)
public class MetodoPrivadoTest {
	private Usuario usuario;
	 
    @Before
    public void setUp() {
        usuario = PowerMockito.spy(new Usuario());
    }
    
    @Test public void testMetodoPrivado() throws Exception {        
        usuario.setUsuario("fabricio");
        usuario.setSenha("fabricio123");
        usuario.setId(1);
        usuario.setNomeCompleto("Fabrício");
        
        // mock de metodo privado
        PowerMockito.doReturn("abcdefg")
        	.when(usuario, "segredo");
        
        assertEquals("abcdefg", usuario.getSegredo());
    }
}
